"""is verified

Revision ID: 5c9779ab9e1a
Revises: 17c43edce4e9
Create Date: 2020-07-31 05:25:39.274553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9779ab9e1a'
down_revision = '17c43edce4e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'user_table', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_table', type_='unique')
    op.drop_column('user_table', 'is_verified')
    # ### end Alembic commands ###
